name: Accessebility Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  accessebility_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nfa/accessebility

    steps:
      # Checkout Code aus dem Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setze die Java-Umgebung auf
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Abhängigkeiten herunterladen und Projekt bauen
      - name: Build with Maven
        run: mvn clean install

      # JUnit-Tests ausführen
      - name: Run tests
        run: mvn test
