name: Angular Tests

on:
  workflow_call:

jobs:
  angular_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./conduit/frontend

    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn run eslint . --ext .js,.jsx,.ts,.tsx
      - name: Run tests
        run: npm run test