  name: Angular Tests

  on:
    workflow_call:

  jobs:
    angular_tests:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./conduit/frontend

      steps:
        - uses: actions/checkout@v4
        - name: Install modules
          run: yarn
        - name: Run ESLint
          run: yarn run eslint . --ext .js,.jsx,.ts,.tsx
          continue-on-error: true
        - name: Run test
          run: npm run test
          continue-on-error: true
