name: Build and publish

on:
  workflow_call:

jobs:
  docker_build_job:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Set Docker tag based on branch
        id: vars
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "BRANCH_TAG=latest" >> $GITHUB_ENV
          else
            BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's/refs\/heads\///')
            echo "BRANCH_TAG=${BRANCH_NAME}" >> $GITHUB_ENV
          fi

      - name: Build Docker Image and publish to docker hub
        working-directory: ./conduit
        run: docker buildx build -t ghcr.io/spirittesting/workshop-pipeline:${{ env.BRANCH_TAG }} -f Dockerfile . ;
          docker push ghcr.io/spirittesting/workshop-pipeline:${{ env.BRANCH_TAG }} ;