name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['master', 'deploy', 'ci-playground']

  push:
    branches: ['master', 'deploy', 'ci-playground']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  angular_tests_job:
    uses: ./.github/workflows/angular-tests.yaml

  django_tests_job:
    uses: ./.github/workflows/django-tests.yaml

  linter_job:
    uses: ./.github/workflows/linter.yaml

  docker_build_job:
    needs: [angular_tests_job, django_tests_job, linter_job]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker buildx build -t spirit/conduit -f conduit/Dockerfile .