name: Django Tests

on:
  workflow_call:

jobs:
  django_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./conduit/backend

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django Tests
        run: python manage.py test