name: ZAP Security Scan

on:
  workflow_call:

jobs:
  zap_scan:
    runs-on: ubuntu-latest  # Definiert die Umgebung für den Job.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Checkout des Repositories.

      # Setze die Java-Umgebung auf
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install OWASP ZAP
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.13.0/ZAP_2.13.0_Linux.tar.gz
          tar -xvzf ZAP_2.13.0_Linux.tar.gz
          sudo mv ZAP_2.13.0 /opt/zap

      - name: Run ZAP security scan
        run: |
          # Starte ZAP im Hintergrund
          /opt/zap/zap.sh -daemon -port 8080

          # Warten, bis ZAP gestartet ist
          sleep 20

          # Führe einen einfachen Web-Security-Scan aus
          /opt/zap/zap-cli quick-scan -t https://workshop.spirit-indianer.com

          # Scan mit detaillierteren Optionen (optional)
          # /opt/zap/zap-cli active-scan -t https://workshop.spirit-indianer.com
        continue-on-error: true


      - name: Archive ZAP Report
        run: |
          # Speichere den ZAP-Bericht
          /opt/zap/zap-cli report -o zap_report.html
          mkdir -p reports
          mv zap_report.html reports/

      - name: Upload ZAP Report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: reports/zap_report.html
        continue-on-error: true
